# Generated by Django 5.1.5 on 2025-03-23 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_book'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={},
        ),
        migrations.AlterModelManagers(
            name='admin',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='admin',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='book',
            name='available_copies',
        ),
        migrations.AlterField(
            model_name='admin',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
