# Generated by Django 5.1.5 on 2025-03-23 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_book'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='adminuser',
            managers=[
            ],
        ),
    ]
